INSERT INTO public.premises (group_id, name, description, sort_order, axis_key)
SELECT g.id, v.name, v.description, v.sort_order, v.axis_key
FROM (VALUES
('filosofia/metafisica/ontologia/agencia/determinismo', 1, 'free_will', 'Não existe livre-arbítrio metafísico', 'Todo evento, inclusive decisões humanas, é consequência necessária de estados anteriores e leis naturais.'),
  ('filosofia/metafisica/ontologia/agencia/determinismo', 2, 'moral_responsibility', 'Responsabilidade moral deve ser reconcebida', 'Elogio e culpa só fazem sentido como instrumentos de previsão e influência social, não como mérito metafísico.'),
  ('filosofia/metafisica/ontologia/agencia/determinismo', 3, 'agency_illusion', 'A sensação de escolha é epifenômeno', 'A experiência subjetiva de poder ter agido de outro modo não prova possibilidade real alternativa.'),
  ('filosofia/metafisica/ontologia/agencia/compatibilismo', 1, 'free_will', 'Livre-arbítrio é compatível com determinismo', 'Agir livremente é agir segundo razões, desejos e caráter próprios, ainda que causalmente determinados.'),
  ('filosofia/metafisica/ontologia/agencia/compatibilismo', 2, 'moral_responsibility', 'Responsabilidade moral é sustentável', 'Podemos responsabilizar agentes quando suas ações expressam razões e controle racional suficiente.'),
  ('filosofia/metafisica/ontologia/agencia/compatibilismo', 3, 'agency_illusion', 'A experiência de agência é informativa', 'A fenomenologia da escolha acompanha mecanismos reais de deliberação e autocontrole.'),
  ('filosofia/metafisica/ontologia/agencia/libertarianismo', 1, 'free_will', 'Existe livre-arbítrio genuino', 'Agentes podem iniciar cadeias causais e realmente poderiam ter feito diferente nas mesmas condições.'),
  ('filosofia/metafisica/ontologia/agencia/libertarianismo', 2, 'moral_responsibility', 'Mérito moral exige indeterminismo agentivo', 'Culpa e louvor pressupõem que o agente não estava absolutamente determinado a agir assim.'),
  ('filosofia/metafisica/ontologia/agencia/libertarianismo', 3, 'agency_illusion', 'A escolha consciente é causalmente eficaz', 'Decisões conscientes não são meros ecos de processos impessoais anteriores.'),
  ('filosofia/metafisica/ontologia/substancia/materialismo', 1, 'mind_matter', 'Tudo o que existe é físico', 'Não há substâncias ou propriedades irredutivelmente não físicas.'),
  ('filosofia/metafisica/ontologia/substancia/materialismo', 2, 'consciousness_base', 'A consciência depende do físico', 'Estados mentais supervêm ou se identificam com estados cerebrais/físicos.'),
  ('filosofia/metafisica/ontologia/substancia/materialismo', 3, 'ontology_priority', 'A física fundamental descreve a base do real', 'Explicações últimas devem ser compatíveis com a imagem científica do mundo.'),
  ('filosofia/metafisica/ontologia/substancia/dualismo', 1, 'mind_matter', 'Mente e matéria são irredutivelmente distintas', 'Propriedades mentais não se esgotam em descrições físicas.'),
  ('filosofia/metafisica/ontologia/substancia/dualismo', 2, 'consciousness_base', 'A consciência não é meramente física', 'Há um aspecto qualitativo da experiência que a física atual não captura.'),
  ('filosofia/metafisica/ontologia/substancia/dualismo', 3, 'ontology_priority', 'O mental tem estatuto ontológico próprio', 'Pessoas e mentes não são apenas arranjos de partículas.'),
  ('filosofia/metafisica/ontologia/substancia/idealismo', 1, 'mind_matter', 'A realidade é fundamentalmente mental', 'O físico é aparência, construção ou dependência do mental.'),
  ('filosofia/metafisica/ontologia/substancia/idealismo', 2, 'consciousness_base', 'A consciência é ontologicamente básica', 'Não se reduz a processos materiais independentes da mente.'),
  ('filosofia/metafisica/ontologia/substancia/idealismo', 3, 'ontology_priority', 'O mental tem prioridade explicativa', 'Explicar o mundo começa pela experiência e pelo sujeito.'),
  ('filosofia/metafisica/ontologia/substancia/panpsiquismo', 1, 'mind_matter', 'A mente está disseminada na natureza', 'Propriedades proto-mentais ou experienciais existem em níveis fundamentais.'),
  ('filosofia/metafisica/ontologia/substancia/panpsiquismo', 2, 'consciousness_base', 'A consciência emerge de combinações de microexperiências', 'O mental humano não surge do absolutamente não-mental.'),
  ('filosofia/metafisica/ontologia/substancia/panpsiquismo', 3, 'ontology_priority', 'Físico e mental são aspectos cooriginários', 'Uma ontologia adequada integra ambos sem eliminar o mental.'),
  ('filosofia/metafisica/ontologia/temporalidade/presentismo', 1, 'time_ontology', 'Só o presente existe', 'Passado e futuro não são reais da mesma forma que o agora.'),
  ('filosofia/metafisica/ontologia/temporalidade/presentismo', 2, 'temporal_change', 'A passagem do tempo é objetiva', 'Há um agora privilegiado que avança genuinamente.'),
  ('filosofia/metafisica/ontologia/temporalidade/presentismo', 3, 'temporal_truth', 'Verdades sobre o passado dependem de rastros presentes', 'Afirmações sobre o que foi dependem do que existe agora.'),
  ('filosofia/metafisica/ontologia/temporalidade/eternalismo', 1, 'time_ontology', 'Passado, presente e futuro são igualmente reais', 'Todos os eventos ocupam posições no bloco espaço-temporal.'),
  ('filosofia/metafisica/ontologia/temporalidade/eternalismo', 2, 'temporal_change', 'A passagem do tempo é perspectival', 'O “fluxo” reflete nossa localização temporal, não uma exclusão ontológica.'),
  ('filosofia/metafisica/ontologia/temporalidade/eternalismo', 3, 'temporal_truth', 'Verdades temporais são indexadas a posições no bloco', 'Fatos sobre qualquer tempo existem no mesmo sentido.'),
  ('filosofia/metafisica/ontologia/temporalidade/growing-block', 1, 'time_ontology', 'Passado e presente existem; o futuro não', 'O bloco do ser cresce à medida que novos eventos se tornam presentes.'),
  ('filosofia/metafisica/ontologia/temporalidade/growing-block', 2, 'temporal_change', 'Há crescimento objetivo da realidade', 'O tornar-se presente acrescenta ser ao mundo.'),
  ('filosofia/metafisica/ontologia/temporalidade/growing-block', 3, 'temporal_truth', 'O futuro é ontologicamente aberto', 'Ainda não há fatos futuros completos no mesmo sentido dos passados.'),
  ('filosofia/metafisica/ontologia/abstracao/realismo-platonico', 1, 'universals', 'Universais e abstratos existem', 'Números, propriedades e relações têm realidade além dos particulares concretos.'),
  ('filosofia/metafisica/ontologia/abstracao/realismo-platonico', 2, 'math_ontology', 'Entidades matemáticas são descobertas', 'A matemática descreve um domínio objetivo independente da mente.'),
  ('filosofia/metafisica/ontologia/abstracao/realismo-platonico', 3, 'shared_properties', 'Objetos distintos compartilham propriedades reais', 'A vermelhidão comum não é só um nome conveniente.'),
  ('filosofia/metafisica/ontologia/abstracao/nominalismo', 1, 'universals', 'Não existem universais reais', 'Só há particulares; predicados gerais são convenções linguísticas ou semelhanças.'),
  ('filosofia/metafisica/ontologia/abstracao/nominalismo', 2, 'math_ontology', 'A matemática é útil, não um reino platônico', 'Números não exigem existência abstrata independente.'),
  ('filosofia/metafisica/ontologia/abstracao/nominalismo', 3, 'shared_properties', 'Semelhança não implica entidades compartilhadas', 'Classificar objetos juntos não cria um universal correspondente.'),
  ('filosofia/metafisica/cosmologia/cosmogenese/naturalismo', 1, 'cosmogenesis', 'A origem do cosmos é natural', 'Não é necessário invocar um agente sobrenatural criador.'),
  ('filosofia/metafisica/cosmologia/cosmogenese/naturalismo', 2, 'divine_action', 'Não há intervenção divina no mundo', 'Explicações científicas bastam para a ordem natural.'),
  ('filosofia/metafisica/cosmologia/cosmogenese/naturalismo', 3, 'ultimate_ground', 'O fundamento último é imanente', 'A realidade se explica sem transcendência pessoal.'),
  ('filosofia/metafisica/cosmologia/cosmogenese/teismo', 1, 'cosmogenesis', 'Há um Deus criador pessoal', 'O universo depende de um ser necessário, consciente e intencional.'),
  ('filosofia/metafisica/cosmologia/cosmogenese/teismo', 2, 'divine_action', 'Deus pode agir no mundo', 'A providência e/ou milagres são metafisicamente possíveis.'),
  ('filosofia/metafisica/cosmologia/cosmogenese/teismo', 3, 'ultimate_ground', 'O fundamento último é transcendente e pessoal', 'A ordem e a existência apontam para inteligência divina.'),
  ('filosofia/metafisica/cosmologia/cosmogenese/panteismo', 1, 'cosmogenesis', 'Deus e o universo não são radicalmente distintos', 'O divino se identifica com a totalidade do real ou o permeia.'),
  ('filosofia/metafisica/cosmologia/cosmogenese/panteismo', 2, 'divine_action', 'O sagrado opera como natureza do todo', 'Não há um criador externo separado da criação.'),
  ('filosofia/metafisica/cosmologia/cosmogenese/panteismo', 3, 'ultimate_ground', 'O fundamento é a unidade do ser', 'Tudo participa de uma realidade divina imanente.'),
  ('filosofia/metafisica/cosmologia/pluralidade/multiverso', 1, 'cosmic_fine_tuning', 'Há uma pluralidade de universos', 'Nosso cosmos é um entre muitos domínios com leis/constantes variadas.'),
  ('filosofia/metafisica/cosmologia/pluralidade/multiverso', 2, 'anthropic_status', 'O ajuste fino é seleção observacional', 'Parece fino porque só universos habitáveis são observados.'),
  ('filosofia/metafisica/cosmologia/pluralidade/multiverso', 3, 'cosmos_uniqueness', 'Nosso universo não é ontologicamente único', 'Não há privilégio metafísico de um único cosmos.'),
  ('filosofia/metafisica/cosmologia/pluralidade/principio-antropico', 1, 'cosmic_fine_tuning', 'O ajuste fino exige explicação especial', 'As condições para a vida não são mera coincidência casual.'),
  ('filosofia/metafisica/cosmologia/pluralidade/principio-antropico', 2, 'anthropic_status', 'O princípio antrópico destaca restrições reais', 'Observadores só existem sob parâmetros estreitos e isso informa cosmologia.'),
  ('filosofia/metafisica/cosmologia/pluralidade/principio-antropico', 3, 'cosmos_uniqueness', 'Nosso universo tem relevância explicativa privilegiada', 'A habitabilidade não deve ser dissolvida apenas em pluralidade especulativa.'),
  ('filosofia/metafisica/cosmologia/finalidade/teleologia', 1, 'natural_purpose', 'Há finalidade na natureza', 'Processos naturais podem ser inteligivelmente descritos como orientados a fins.'),
  ('filosofia/metafisica/cosmologia/finalidade/teleologia', 2, 'explanation_type', 'Explicações por fins são legítimas', 'Nem toda explicação boa se reduz a mecanismos cegos.'),
  ('filosofia/metafisica/cosmologia/finalidade/teleologia', 3, 'design_signal', 'Ordem funcional sugere direção', 'Organização complexa aponta para teleologia real ou irredutível.'),
  ('filosofia/metafisica/cosmologia/finalidade/mecanicismo', 1, 'natural_purpose', 'Não há fins intrínsecos na natureza', 'Causas eficientes e leis bastam; finalidade é projeção humana.'),
  ('filosofia/metafisica/cosmologia/finalidade/mecanicismo', 2, 'explanation_type', 'Explicações mecânicas têm prioridade', 'Apelos a propósitos devem ser traduzidos em mecanismos.'),
  ('filosofia/metafisica/cosmologia/finalidade/mecanicismo', 3, 'design_signal', 'Ordem não implica propósito cósmico', 'Complexidade surge de processos não teleológicos.'),
  ('politica/ideologias/liberalismo', 1, 'property_rights', 'Direitos individuais e propriedade privada são centrais', 'Liberdades civis e econômicas protegem a autonomia frente ao Estado e a maiorias.'),
  ('politica/ideologias/liberalismo', 2, 'market_vs_plan', 'Mercados voluntários alocam melhor recursos', 'Trocas livres e concorrência superam planejamento central amplo.'),
  ('politica/ideologias/liberalismo', 3, 'state_role', 'O Estado deve ser limitado', 'Funções estatais se concentram em regras gerais, direitos e bens públicos essenciais.')
) AS v(slug, sort_order, axis_key, name, description)
JOIN public.groups g ON g.slug = v.slug AND g.is_open = false;
