INSERT INTO public.premises (group_id, name, description, sort_order, axis_key)
SELECT g.id, v.name, v.description, v.sort_order, v.axis_key
FROM (VALUES
  ('politica/ideologias/libertarianismo', 1, 'property_rights', 'Autopropriedade e propriedade justa são invioláveis', 'Agressão iniciatória contra pessoas e haveres legítimos é ilegítima.'),
  ('politica/ideologias/libertarianismo', 2, 'market_vs_plan', 'Ordem espontânea de mercado é preferível', 'Intervenção coercitiva distorce informação e liberdade.'),
  ('politica/ideologias/libertarianismo', 3, 'state_role', 'O poder estatal deve ser mínimo ou nulo', 'Impostos e regulações coercitivas exigem justificativa excepcional.'),
  ('politica/ideologias/socialismo', 1, 'property_rights', 'A propriedade dos meios de produção deve ser social', 'Controle privado amplo desses meios gera exploração e desigualdade injusta.'),
  ('politica/ideologias/socialismo', 2, 'market_vs_plan', 'Coordenação democrática/social supera o mercado irrestrito', 'Necessidades humanas não devem ficar só ao sabor do lucro.'),
  ('politica/ideologias/socialismo', 3, 'state_role', 'Ação coletiva forte é necessária', 'Instituições públicas devem garantir igualdade substantiva e bens sociais.'),
  ('politica/ideologias/comunismo', 1, 'property_rights', 'Abolir a propriedade privada dos meios de produção', 'Classes e exploração cessam com propriedade comum dos meios produtivos.'),
  ('politica/ideologias/comunismo', 2, 'market_vs_plan', 'A produção deve orientar-se ao uso comum', 'O mercado capitalista não é o horizonte final da organização econômica.'),
  ('politica/ideologias/comunismo', 3, 'state_role', 'O Estado de classe deve ser superado', 'A emancipação aponta para uma sociedade sem dominação de classe.'),
  ('politica/ideologias/social-democracia', 1, 'property_rights', 'Mercado e propriedade privada com correções sociais', 'Aceita-se economia de mercado regulada sob forte redistribuição.'),
  ('politica/ideologias/social-democracia', 2, 'market_vs_plan', 'Capitalismo regulado com Estado de bem-estar', 'Direitos sociais amplos complementam (e limitam) o mercado.'),
  ('politica/ideologias/social-democracia', 3, 'state_role', 'Estado democrático robusto é desejável', 'Serviços públicos, tributação progressiva e regulação são legítimos.'),
  ('politica/ideologias/conservadorismo', 1, 'social_change', 'Tradições e instituições herdadas têm sabedoria acumulada', 'Mudanças abruptas arriscam erosão de ordem e sentido social.'),
  ('politica/ideologias/conservadorismo', 2, 'authority_custom', 'Autoridade, costume e continuidade importam', 'Normas espontâneas e herança cultural estabilizam a vida comum.'),
  ('politica/ideologias/conservadorismo', 3, 'human_nature_politics', 'A natureza humana é limitada e imperfeita', 'Política deve ser prudente ante utopias de transformação total.'),
  ('politica/ideologias/progressismo', 1, 'social_change', 'Reformas progressivas são moralmente urgentes', 'Instituições devem atualizar-se para ampliar inclusão e justiça.'),
  ('politica/ideologias/progressismo', 2, 'authority_custom', 'Costume não justifica opressão', 'Tradições devem ser criticadas quando perpetuam desigualdades.'),
  ('politica/ideologias/progressismo', 3, 'human_nature_politics', 'Arranjos sociais são moldáveis', 'Política pode melhorar substancialmente condições e relações de poder.'),
  ('politica/ideologias/anarquismo', 1, 'state_legitimacy', 'O Estado é uma forma ilegítima de dominação', 'Hierarquias coercitivas centralizadas devem ser rejeitadas.'),
  ('politica/ideologias/anarquismo', 2, 'voluntary_order', 'Ordem pode surgir sem governo', 'Associações voluntárias e mutualismo sustentam cooperação.'),
  ('politica/ideologias/anarquismo', 3, 'hierarchy', 'Hierarquias injustificadas devem ser desmanteladas', 'Autoridade só se justifica por consentimento e utilidade evidentes.'),
  ('politica/ideologias/anarquismo/anarcocapitalismo', 1, 'post_state_property', 'Propriedade privada permanece sem Estado', 'Mercados e defesa privada podem substituir monopólio estatal.'),
  ('politica/ideologias/anarquismo/anarcocapitalismo', 2, 'state_legitimacy', 'O Estado viola direitos de propriedade', 'Imposto e monopólio da força são agressões institucionalizadas.'),
  ('politica/ideologias/anarquismo/anarcocapitalismo', 3, 'voluntary_order', 'Ordem de mercado espontânea basta', 'Contratos e concorrência geram normas e segurança.'),
  ('politica/ideologias/anarquismo/anarcocomunismo', 1, 'post_state_property', 'Propriedade privada capitalista deve ser abolida', 'Sem Estado, a economia se organiza pelo comum e pela necessidade.'),
  ('politica/ideologias/anarquismo/anarcocomunismo', 2, 'state_legitimacy', 'Estado e capital são dominações conjugadas', 'Libertar-se exige superar ambos.'),
  ('politica/ideologias/anarquismo/anarcocomunismo', 3, 'voluntary_order', 'Comunismo libertário é ordem voluntária', 'Mutualidade e autogestão substituem mercado e governo.'),
  ('politica/ideologias/feminismo', 1, 'gender_equality', 'Há desigualdade estrutural de gênero a combater', 'Relações de poder entre gêneros não são apenas preferências individuais.'),
  ('politica/ideologias/feminismo', 2, 'gender_politics', 'O pessoal é político', 'Família, trabalho e corpo são arenas legítimas de contestação política.'),
  ('politica/ideologias/feminismo', 3, 'gender_emancipation', 'Emancipação de gênero é objetivo coletivo', 'Direitos formais não bastam sem transformação social.'),
  ('politica/ideologias/ambientalismo', 1, 'eco_priority', 'Limites ecológicos devem restringir a política econômica', 'Crescimento e consumo não podem ignorar capacidade do planeta.'),
  ('politica/ideologias/ambientalismo', 2, 'eco_value', 'A natureza tem valor moral/político relevante', 'Não é apenas recurso instrumental ilimitado.'),
  ('politica/ideologias/ambientalismo', 3, 'eco_action', 'Ação coletiva ambiental é urgente', 'Regulação e coordenação são necessárias ante danos sistêmicos.'),
  ('politica/sistemas-de-governo/formas-de-governo/monarquia', 1, 'sovereign_form', 'A soberania personificada é legítima', 'Um monarca pode simbolizar e estabilizar a continuidade do Estado.'),
  ('politica/sistemas-de-governo/formas-de-governo/monarquia', 2, 'succession_principle', 'Sucessão hereditária ou dinástica pode ser desejável', 'Previsibilidade sucessória reduz disputas pelo poder máximo.'),
  ('politica/sistemas-de-governo/formas-de-governo/monarquia', 3, 'political_unity', 'Unidade política se beneficia de um vértice pessoal', 'A figura do monarca concentra representação da nação.'),
  ('politica/sistemas-de-governo/formas-de-governo/republica', 1, 'sovereign_form', 'A soberania reside no povo via instituições', 'Cargos públicos não devem ser propriedade hereditária.'),
  ('politica/sistemas-de-governo/formas-de-governo/republica', 2, 'succession_principle', 'Mandatos eletivos e temporários são preferíveis', 'Alternância institucional limita personalização permanente do poder.'),
  ('politica/sistemas-de-governo/formas-de-governo/republica', 3, 'political_unity', 'Unidade se constrói por lei e cidadania', 'A res publica, não uma dinastia, articula o comum político.'),
  ('politica/sistemas-de-governo/formas-de-governo/anarquia', 1, 'sovereign_form', 'Não deve haver soberano coercitivo central', 'A ausência de governo é preferível a qualquer monopólio da força.'),
  ('politica/sistemas-de-governo/formas-de-governo/anarquia', 2, 'succession_principle', 'Não há trono ou cargo soberano a suceder', 'Poder político permanente concentrado é indesejável.'),
  ('politica/sistemas-de-governo/formas-de-governo/anarquia', 3, 'political_unity', 'Unidade política coercitiva não é necessária', 'Comunidades voluntárias bastam à cooperação.'),
  ('politica/sistemas-de-governo/formas-de-governo/teocracia', 1, 'sovereign_form', 'A soberania última é divina', 'A lei religiosa/moral transcendente deve ordenar o poder político.'),
  ('politica/sistemas-de-governo/formas-de-governo/teocracia', 2, 'succession_principle', 'Autoridade política deriva de legitimidade religiosa', 'Quem governa o faz sob mandato sagrado ou interpretação autorizada.'),
  ('politica/sistemas-de-governo/formas-de-governo/teocracia', 3, 'political_unity', 'Unidade política e religiosa se integram', 'Separar completamente fé e ordem pública enfraquece o bem comum teológico.'),
  ('politica/sistemas-de-governo/formas-de-estado/federalismo', 1, 'territorial_power', 'O poder deve ser dividido entre esfera central e unidades', 'Autonomias federadas protegem diversidade e limitam concentração.'),
  ('politica/sistemas-de-governo/formas-de-estado/federalismo', 2, 'local_autonomy', 'Entes subnacionais têm competência própria', 'Nem tudo deve ser decidido no centro.'),
  ('politica/sistemas-de-governo/formas-de-estado/federalismo', 3, 'constitutional_division', 'A divisão territorial do poder é constitucional', 'Competências são garantidas contra usurpação unilateral.'),
  ('politica/sistemas-de-governo/formas-de-estado/confederalismo', 1, 'territorial_power', 'A soberania principal permanece nas unidades', 'O centro é delegação frágil dos membros soberanos.'),
  ('politica/sistemas-de-governo/formas-de-estado/confederalismo', 2, 'local_autonomy', 'Máxima autonomia das partes associadas', 'O vínculo confederal é voluntário e reversível em espírito.'),
  ('politica/sistemas-de-governo/formas-de-estado/confederalismo', 3, 'constitutional_division', 'O centro não deve absorver as partes', 'Instituições comuns servem coordenação, não hierarquia rígida.'),
  ('politica/sistemas-de-governo/formas-de-estado/unitarismo', 1, 'territorial_power', 'A soberania é una e indivisível no centro', 'Unidades locais exercem poder derivado, não soberano.'),
  ('politica/sistemas-de-governo/formas-de-estado/unitarismo', 2, 'local_autonomy', 'Autonomia local é administrativa, não soberana', 'Pode haver descentralização, sem federalização da soberania.'),
  ('politica/sistemas-de-governo/formas-de-estado/unitarismo', 3, 'constitutional_division', 'Unidade jurídica nacional é prioritária', 'Fragmentar soberania enfraquece coerência estatal.'),
  ('politica/sistemas-de-governo/regimes-politicos/democracia', 1, 'regime_legitimacy', 'Legitimidade vem do consentimento popular', 'Governo justo depende de participação e accountability eleitoral.'),
  ('politica/sistemas-de-governo/regimes-politicos/democracia', 2, 'power_access', 'Cidadãos devem poder influenciar o poder', 'Direitos políticos amplos são essenciais.'),
  ('politica/sistemas-de-governo/regimes-politicos/democracia', 3, 'regime_limits', 'Maiorias também precisam de limites', 'Direitos e instituições protegem minorias e o próprio processo democrático.'),
  ('politica/sistemas-de-governo/regimes-politicos/autocracia', 1, 'regime_legitimacy', 'Concentração decisória em um centro é eficaz', 'Unidade de comando pode superar paralisia pluralista.'),
  ('politica/sistemas-de-governo/regimes-politicos/autocracia', 2, 'power_access', 'Acesso amplo ao poder não é necessário', 'Governo pode ser legítimo sem contestação eleitoral aberta.'),
  ('politica/sistemas-de-governo/regimes-politicos/autocracia', 3, 'regime_limits', 'Ordem e autoridade prevalecem sobre dispersão', 'Restrições à contestação podem ser justificadas pela estabilidade.')
) AS v(slug, sort_order, axis_key, name, description)
JOIN public.groups g ON g.slug = v.slug AND g.is_open = false;
