INSERT INTO public.premises (group_id, name, description, sort_order, axis_key)
SELECT g.id, v.name, v.description, v.sort_order, v.axis_key
FROM (VALUES
  ('politica/sistemas-de-governo/regimes-politicos/oligarquia', 1, 'regime_legitimacy', 'Uma elite competente deve dirigir', 'Nem todos devem ter peso igual nas decisões políticas centrais.'),
  ('politica/sistemas-de-governo/regimes-politicos/oligarquia', 2, 'power_access', 'O poder cabe a poucos qualificados', 'Mérito, riqueza ou status podem filtrar quem governa.'),
  ('politica/sistemas-de-governo/regimes-politicos/oligarquia', 3, 'regime_limits', 'Massas amplas não devem dominar a política', 'Evitar captura por maiorias incompetentes ou voláteis.'),
  ('religiao/ateismo', 1, 'god_exists', 'Deus não existe', 'Não há ser divino real que sustente o mundo ou a moral.'),
  ('religiao/ateismo', 2, 'religious_authority', 'Autoridade religiosa não obriga', 'Doutrinas reveladas não têm autoridade epistêmica especial.'),
  ('religiao/ateismo', 3, 'afterlife', 'Não há vida após a morte sobrenatural', 'A existência pessoal cessa com a morte biológica.'),
  ('religiao/agnosticismo', 1, 'god_exists', 'A existência de Deus é desconhecida ou indecidível', 'Não se afirma teísmo nem ateísmo como certeza.'),
  ('religiao/agnosticismo', 2, 'religious_authority', 'Suspensão do juízo ante revelações', 'Falta evidência suficiente para aderir dogmaticamente.'),
  ('religiao/agnosticismo', 3, 'afterlife', 'O pós-morte permanece incerto', 'Não se compromete com céu, reencarnação ou aniquilação dogmática.'),
  ('religiao/deismo', 1, 'god_exists', 'Há um criador racional, não necessariamente revelado', 'Deus se conhece sobretudo pela razão/natureza, não por dogmas.'),
  ('religiao/deismo', 2, 'religious_authority', 'Revelações positivas são suspeitas', 'Religiões históricas não têm monopólio da verdade divina.'),
  ('religiao/deismo', 3, 'divine_action', 'Deus não intervém rotineiramente', 'O mundo segue leis sem milagres providenciais constantes.'),
  ('religiao/monoteismo', 1, 'god_exists', 'Há um único Deus', 'A divindade é una, não um panteão de deuses últimos.'),
  ('religiao/monoteismo', 2, 'religious_authority', 'Há revelação ou relação válida com o Uno', 'O monoteísmo estrutura culto, moral e comunidade.'),
  ('religiao/monoteismo', 3, 'divine_unity', 'Somente um ser divino absoluto', 'Outros “deuses” não compartilham a soberania última.'),
  ('religiao/politeismo', 1, 'god_exists', 'Há múltiplas divindades reais', 'O sagrado se manifesta em vários deuses/poderes.'),
  ('religiao/politeismo', 2, 'religious_authority', 'Cultos plurais são legítimos', 'Não há um único deus exclusivo como única via.'),
  ('religiao/politeismo', 3, 'divine_unity', 'A pluralidade divina é ontologicamente genuína', 'Reduzir tudo a um único Deus apaga diferenças reais.'),
  ('religiao/monoteismo/cristianismo', 1, 'christ_revelation', 'Jesus Cristo é revelação central de Deus', 'A fé cristã se organiza em torno da pessoa e obra de Cristo.'),
  ('religiao/monoteismo/cristianismo', 2, 'scripture_tradition', 'Escrituras cristãs têm autoridade', 'O cânone cristão orienta crença e prática.'),
  ('religiao/monoteismo/cristianismo', 3, 'salvation', 'Há salvação em Cristo', 'O destino humano se resolve na economia cristã da graça.'),
  ('religiao/monoteismo/cristianismo/catolicismo', 1, 'church_authority', 'A Igreja Católica tem autoridade apostólica', 'Magistério e tradição interpretam legitimamente a fé.'),
  ('religiao/monoteismo/cristianismo/catolicismo', 2, 'sacraments', 'Os sacramentos são meios eficazes de graça', 'Eucaristia e demais sacramentos têm realidade sacramental.'),
  ('religiao/monoteismo/cristianismo/catolicismo', 3, 'papacy_mary', 'Papado e doutrina mariana são parte da fé', 'Estruturas e dogmas católicos não são acidentais.'),
  ('religiao/monoteismo/cristianismo/protestantismo', 1, 'church_authority', 'A Escritura tem primazia sobre o magistério romano', 'Sola scriptura (em suas variantes) limita autoridade eclesiástica.'),
  ('religiao/monoteismo/cristianismo/protestantismo', 2, 'sacraments', 'Os sacramentos não seguem o sistema católico pleno', 'Rejeitam-se dogmas sacramentais e mediacionais específicos de Roma.'),
  ('religiao/monoteismo/cristianismo/protestantismo', 3, 'papacy_mary', 'Papado e dogmas marianos católicos não obrigam', 'A fé protestante dispensa essas exigências.'),
  ('religiao/monoteismo/islamismo', 1, 'prophetic_finality', 'Maomé é o último profeta', 'O Alcorão é revelação definitiva a ser seguida.'),
  ('religiao/monoteismo/islamismo', 2, 'tawhid', 'A unicidade absoluta de Deus (tawhid)', 'Não há associação (shirk) com Allah.'),
  ('religiao/monoteismo/islamismo', 3, 'sharia_practice', 'A prática islâmica ordena a vida do crente', 'Ibadat e normas reveladas estruturam a piedade.'),
  ('religiao/monoteismo/judaismo', 1, 'covenant_israel', 'A aliança com Israel é central', 'Torá e povo judeu estruturam a relação com Deus.'),
  ('religiao/monoteismo/judaismo', 2, 'torah_authority', 'A Torá tem autoridade normativa', 'Lei e interpretação judaica orientam a vida fiel.'),
  ('religiao/monoteismo/judaismo', 3, 'messiah_status', 'A esperança messiânica judaica não se identifica com Jesus', 'O messianismo cristão não é aceito como cumprimento.'),
  ('religiao/politeismo/hinduismo', 1, 'dharma_karma', 'Dharma e carma ordenam a realidade moral', 'Ações têm consequências além da vida imediata.'),
  ('religiao/politeismo/hinduismo', 2, 'divine_plurality_forms', 'O divino assume múltiplas formas', 'Deidades e avatares expressam o sagrado.'),
  ('religiao/politeismo/hinduismo', 3, 'moksha', 'Há libertação do ciclo de renascimentos', 'Moksha é horizonte soteriológico legítimo.'),
  ('religiao/politeismo/xintoismo', 1, 'kami_reality', 'Kami são realidades veneráveis', 'O sagrado habita lugares, antepassados e forças naturais.'),
  ('religiao/politeismo/xintoismo', 2, 'ritual_purity', 'Ritual e pureza importam', 'Práticas xintoístas mantêm harmonia com o sagrado.'),
  ('religiao/politeismo/xintoismo', 3, 'local_sacred', 'O sagrado é fortemente local e imanente', 'Santuários e terra têm densidade espiritual própria.'),
  ('religiao/budismo', 1, 'four_truths', 'As Quatro Nobres Verdades são fundamentais', 'Sofrimento, origem, cessação e caminho estruturam a libertação.'),
  ('religiao/budismo', 2, 'anatta_impermanence', 'Não-eu e impermanência', 'Apegar-se a um eu permanente é equívoco.'),
  ('religiao/budismo', 3, 'nirvana_path', 'O Nirvana/libertação é alcançável pelo caminho', 'Prática ética, meditativa e sapiencial conduz à cessação do sofrimento.'),
  ('saude/dietas/vegana', 1, 'animal_products', 'Deve-se evitar produtos de origem animal', 'Ética e/ou saúde justificam dieta sem carne, ovos e laticínios.'),
  ('saude/dietas/vegana', 2, 'diet_health', 'Dieta vegetal bem planejada é adequada', 'Nutrientes necessários podem ser obtidos sem alimentos animais.'),
  ('saude/dietas/vegana', 3, 'diet_ethics', 'Exploração animal alimentar é moralmente problemática', 'Consumir animais é, em geral, evitável e questionável.'),
  ('saude/dietas/carnivora', 1, 'animal_products', 'Alimentos animais são centrais e desejáveis', 'Carne e produtos animais formam a base alimentar preferível.'),
  ('saude/dietas/carnivora', 2, 'diet_health', 'Dieta rica em animalidade pode ser saudável', 'Excluir vegetais não é necessariamente deletério.'),
  ('saude/dietas/carnivora', 3, 'diet_ethics', 'Comer animais é moralmente aceitável', 'Não há dever geral de abster-se de produtos animais.'),
  ('saude/dietas/cetogenica', 1, 'carb_level', 'Carboidratos devem ser drasticamente reduzidos', 'Cetose nutricional é um estado metabólico desejável.'),
  ('saude/dietas/cetogenica', 2, 'diet_macros', 'Gorduras são o combustível principal', 'A dieta privilegia lipídios sobre carboidratos.'),
  ('saude/dietas/cetogenica', 3, 'metabolic_goal', 'Controle glicêmico/cetose é objetivo central', 'Estabilidade metabólica via baixa insulina é prioritária.'),
  ('saude/dietas/low-carb', 1, 'carb_level', 'Carboidratos devem ser limitados', 'Reduzir pães, açúcares e amidos melhora desfechos.'),
  ('saude/dietas/low-carb', 2, 'diet_macros', 'Proteína e gordura ganham espaço relativo', 'Não é necessário alto carboidrato para saúde.'),
  ('saude/dietas/low-carb', 3, 'metabolic_goal', 'Melhorar metabolismo da glicose é central', 'Controle de açúcar e insulina guia a dieta.'),
  ('saude/dietas/paleolitica', 1, 'ancestral_template', 'O modelo ancestral deve orientar a dieta', 'Alimentos pré-agrícolas são o referencial normativo.'),
  ('saude/dietas/paleolitica', 2, 'processed_food', 'Alimentos ultraprocessados e grãos modernos são problemáticos', 'Deve-se priorizar comida “de verdade” ancestralmente plausível.'),
  ('saude/dietas/paleolitica', 3, 'diet_health', 'Adequação evolutiva implica saúde', 'Descompasso com o ambiente alimentar moderno adoece.'),
  ('saude/dietas/mediterranea', 1, 'ancestral_template', 'O padrão mediterrâneo é o referencial', 'Azeite, vegetais, peixes e moderação orientam a dieta.'),
  ('saude/dietas/mediterranea', 2, 'processed_food', 'Qualidade e padrão alimentar importam mais que extremos', 'Equilíbrio e alimentos integrais superam dogmas radicais.'),
  ('saude/dietas/mediterranea', 3, 'diet_health', 'Evidência epidemiológica favorece esse padrão', 'Longevidade e saúde cardiovascular apoiam a abordagem.')
) AS v(slug, sort_order, axis_key, name, description)
JOIN public.groups g ON g.slug = v.slug AND g.is_open = false;
